### ISSUE TITLE
Selection window shows not all items

### ISSUE THREAD

**Issue by StephanSteinert** [Peppe-KSP/production-monitor#2]
Hi,

tried your mod and it seems nice.
I play with Angel's and Bob's mods and i can't select all items, even the science packs are missing, probably because of the huge amount of items.

Can you please have a look at it?

Cu, steinio.

Edit: Notice to me: read the info that the button provides - solid items are displayed after dragging them on the plus button.

**Comment by Peppe-KSP** [comment]
Glad you were able to resolve.  

For others, just liquids have the popup window everything else you just take the item form and drop it on the [+].
